name: mobile_application
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1
environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
    

  
  cupertino_icons: ^1.0.8
  logger: ^2.5.0
  http: ^1.2.2
  fpdart: ^1.1.0
  encrypt: ^5.0.3
  shared_preferences: ^2.3.3
  flutter_secure_storage: ^9.2.2
  get_it: ^8.0.3
  flutter_dotenv: ^5.2.1
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  go_router: ^14.6.2
  flutter_native_splash: ^2.4.3
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0

flutter:
  
  uses-material-design: true
  assets:
    - lib/common/config/.env
    - lib/common/asset/image/
  fonts: 
  - family: Merriweather
    fonts:
      - asset: lib/common/asset/font/Merriweather-Regular.ttf
        style: normal
        weight: 400
      - asset: lib/common/asset/font/Merriweather-Light.ttf
        style: normal
        weight: 200
      - asset: lib/common/asset/font/Merriweather-Italic.ttf
        style: italic
      - asset: lib/common/asset/font/Merriweather-BoldItalic.ttf
        style: italic
        weight: 700
      - asset: lib/common/asset/font/Merriweather-Bold.ttf
        style: normal
        weight: 700
